# Generated by Django 5.0 on 2024-09-27 17:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appHome", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("autor", models.CharField(max_length=100)),
                ("duracao", models.CharField(max_length=100)),
                ("preco", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name="usuario",
            name="email",
            field=models.EmailField(
                max_length=254, validators=[django.core.validators.EmailValidator()]
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="nome",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="senha",
            field=models.CharField(max_length=100),
        ),
    ]
