# Generated by Django 5.0 on 2024-11-04 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appHome", "0003_usuario_groups_usuario_is_active_usuario_is_staff_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usuario",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="last_login",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="password",
        ),
        migrations.RemoveField(
            model_name="usuario",
            name="user_permissions",
        ),
    ]
