# Generated by Django 5.0 on 2024-11-04 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appHome", "0004_remove_usuario_groups_remove_usuario_is_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="senha",
            field=models.CharField(max_length=128),
        ),
    ]
